### ISSUE TITLE
Power On/Off Commands?

### ISSUE THREAD

**Issue by EpicLPer** [zarpli/Logitech-Z906#2]
Heya!

Just wondering reading through the commands, is there a Power On/Off command?

Thanks!

**Comment by zarpli** [comment]
PWM_ON and PWM_OFF

**Comment by EpicLPer** [comment]
Ah, thanks for clarification!

But I think this is a tiny bit confusing even? Cause the Z906 has a built in speaker test function, and at first I thought the "PWM" was meant as this testing function. Maybe calling it "PWR" instead would be easier understandable :)

**Comment by zarpli** [comment]
> Ah, thanks for clarification!
> 
> But I think this is a tiny bit confusing even? Cause the Z906 has a built in speaker test function, and at first I thought the "PWM" was meant as this testing function. Maybe calling it "PWR" instead would be easier understandable :)

can be a bit confusing but this is how class D amplifiers work,

I have left out the speaker test function yet but it is implemented in the DSP firmware.

**Comment by EpicLPer** [comment]
Okay that makes sense then.
Still hope someone can someday implement this into a ESP-friendly firmware, know there is another project currently building upon this research (I think?) but sadly no progress yet. Would love to implement the Z906 directly into my Smart Home :) Would even donate a few bucks if someone does it.

Thanks for the research work and reversing btw!

**Comment by nomis** [comment]
I opened up the console last year and produced [this documentation](https://github.com/nomis/logitech-z906).

I've started on an [ESP32-S2 application](https://github.com/nomis/ggroohauga) that will make this possible but I don't know when it'll be finished. Currently all it does is relay the communication between the two devices.
